<?php

/**
 * Test class for AppPresenter.
 * Generated by PHPUnit on 2011-01-03 at 15:02:38.
 */
class AppPresenterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AppPresenter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AppPresenter;
        $this->object->autoCanonicalize=FALSE;
        //Nette\Environment::getApplication()->setRouter(new \Nette\Application\SimpleRouter());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testActionDefault().
     */
    public function testActionDefault() {
        $request=new \Nette\Application\PresenterRequest("App", "HEAD", array('action'=>'default'));
        $response= $this->object->run($request);
        $this->assertInstanceOf('Nette\\Application\\RenderResponse',$response);
    }

    /**
     * @todo Implement testActionDelete().
     */
    public function testActionDelete() {
        $request=new \Nette\Application\PresenterRequest("App", "HEAD", array('action'=>'delete'));
        $response= $this->object->run($request);
        $this->assertInstanceOf('Nette\\Application\\RedirectingResponse',$response);
    }

    /**
     * @todo Implement testCreateComponentAppGrid().
     */
    public function testCreateComponentAppGrid() {
        $this->assertInstanceOf('Datagrid',$this->object['appGrid']);
    }

    /**
     * @todo Implement testActionAdd().
     */
    public function testActionAdd() {

        $request=new \Nette\Application\PresenterRequest("App", "HEAD", array('action'=>'add'));
        $response= $this->object->run($request);
        $this->assertInstanceOf('Nette\\Application\\RenderResponse',$response);
    }

    /**
     * @todo Implement testActionEdit().
     */
    public function testActionEdit() {

        $request=new \Nette\Application\PresenterRequest("App", "HEAD", array('action'=>'edit'));
        $response= $this->object->run($request);
        $this->assertInstanceOf('Nette\\Application\\RenderResponse',$response);
    }

}

?>
