<?php

/**
 * Test class for DefaultPresenter.
 * Generated by PHPUnit on 2011-01-03 at 15:39:47.
 */
class DefaultPresenterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DefaultPresenter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DefaultPresenter;
        $this->object->autoCanonicalize=FALSE;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    public function testActionDefault() {

        $request=new \Nette\Application\PresenterRequest("Default", "HEAD", array());
        $response= $this->object->run($request);
        $this->assertInstanceOf('Nette\\Application\\RenderResponse',$response);

    }

    /**
     * @todo Implement testActionShowLog().
     */
    public function testActionShowLog() {
        $request=new \Nette\Application\PresenterRequest("Default", "HEAD", array("action"=>'showLog'));
        $response= $this->object->run($request);
        $this->assertInstanceOf('Nette\\Application\\RenderResponse',$response);

        $this->assertInstanceOf('Datagrid',  $this->object['logGrid']);
    }

}

?>
