<?php

/**
 * Test class for KeyDefPresenter.
 * Generated by PHPUnit on 2011-01-03 at 15:39:53.
 */
class KeyDefPresenterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var KeyDefPresenter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new KeyDefPresenter;
        $this->object->autoCanonicalize=FALSE;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testActionDefault().
     */
    public function testActionDefault() {
        $request=new \Nette\Application\PresenterRequest("KeyDef", "HEAD", array());
        $response= $this->object->run($request);
        $this->assertInstanceOf('Nette\\Application\\RenderResponse',$response);
    }

    /**
     * @todo Implement testCreateComponentIndexDefForm().
     */
    public function testCreateComponentIndexDefForm() {
        $this->assertInstanceOf('Nette\\Application\\AppForm',$this->object['indexDefForm']);
    }

}

?>
