<?php

/**
 * Test class for SoapTestPresenter.
 * Generated by PHPUnit on 2011-01-03 at 15:40:06.
 */
class SoapTestPresenterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SoapTestPresenter
     */
    protected $object;
    private $app_id;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SoapTestPresenter;
        $this->object->autoCanonicalize=FALSE;
        $this->app_id=@reset(Application::find())->app_id;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testActionDefault().
     */
    public function testActionDefault() {
        $request = new \Nette\Application\PresenterRequest("SoapTest", "HEAD", array("app_id"=>$this->app_id));
        $response = $this->object->run($request);
        $this->assertInstanceOf('Nette\\Application\\RenderResponse', $response);
    }

    /**
     * @todo Implement testActionTest().
     */
    public function testActionTest() {
        $request = new \Nette\Application\PresenterRequest("SoapTest", "HEAD",
                array(
                    "action"=>'test',
                    "app_id"=>$this->app_id,
                    "met_id"=>@reset(Operation::find(array("app_id" => $this->app_id)))->met_id
                ));
        $response = $this->object->run($request);
        $this->assertInstanceOf('Nette\\Application\\RenderResponse', $response);
    }

    /**
     * @todo Implement testCreateComponentDatagrid().
     */
    public function testCreateComponentDatagrid() {
        $this->assertInstanceOf('Datagrid',$this->object['datagrid']);
    }

    /**
     * @todo Implement testCreateComponentForm().
     */
    public function testCreateComponentForm() {

        $this->assertInstanceOf('Nette\\Application\\AppForm',$this->object['form']);
    }

}

?>
