<?php

/**
 * Test class for IndexDefinition.
 * Generated by PHPUnit on 2011-01-02 at 18:39:24.
 */
class IndexDefinitionTest extends PHPUnit_Framework_TestCase {

    

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers IndexDefinition
     */
    public function testAll() {
        $ret=IndexDefinition::find();
        $this->assertInternalType('array',$ret);
        $this->assertGreaterThan(0,count($ret));
        IndexDefinition::saveAll($ret);
        $this->assertEquals($ret,  IndexDefinition::find());
    }

    

}

?>
