<?php

/**
 * Test class for FixedCliRouter.
 * Generated by PHPUnit on 2011-01-02 at 21:37:04.
 */
class FixedCliRouterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var FixedCliRouter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FixedCliRouter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testMatch().
     */
    public function testMatch() {
        $request=new \Nette\Web\HttpRequest(new \Nette\Web\UriScript("index.php"), NULL, NULL, NULL, NULL, NULL, "CLI", "127.0.0.1", "localhost");
        $_SERVER['argv'][]='Import:import';
        $this->assertInstanceOf("Nette\\Application\\PresenterRequest",$this->object->match($request));
    }

}

?>
