{**
 * My Application layout template.
 *
 * @copyright  Copyright (c) 2010 John Doe
 * @package    MyApplication
 *
 * @param string   $basePath web base path
 * @param string   $robots   tell robots how to index the content of a page (optinal)
 * @param array    $flashes  flash messages
 *}

{control header}

<body>
        <h1>{$control['header']->getTitle()}</h1>
        {control navigation}
	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	{include #content}
</body>
</html>
