<ul class="control ">
	{if $useHomepage}
	<li>
		{if $homepage->isCurrent}
		<span class="active"  class="ui-button ui-state-default ui-corner-all ui-button-text-icon"><strong>{$homepage->label}</strong></span>
		{else}
		<a href="{$homepage->url}"  class="ui-button ui-state-default ui-corner-all ui-button-text-icon">{$homepage->label}</a>
		{/if}
	</li>
	{/if}

	{block #menu}
	{foreach $children as $item}
	<li>
		{if $item->isCurrent}
		<span class="active"  class="ui-button ui-state-default ui-corner-all ui-button-text-icon"  ><strong>{$item->label}</strong></span>
		{else}
		<a href="{$item->url}" class="ui-button ui-state-default ui-corner-all ui-button-text-icon">
                    {$item->label}</a>
		{/if}
		
		{if $renderChildren && count($item->getComponents()) > 0}
		<ul>
			{include #menu, children => $item->getComponents()}
		</ul>
		{/if}
	</li>
	{/foreach}
	{/block}
</ul>